* xsv.el
xsv.el is a front end for CSV toolkit [[https://github.com/BurntSushi/xsv][xsv]]. xsv provides very powerful ways to
work with CSV file and xsv.el brings that awesomeness into Emacs.

* installation
For now, either clone the repo and add to load-path or use package manager like straight.

* Why
Emacs has CSV mode to work with CSV files, it has nice things but I find it
lacking certain functionality I want and I have to resort to Numbers/Excel from
time to time.

After I discovered the xsv, I realize it could bridge the gap I encountered before.

Some examples are:
- I want to filter the csv file to show only rows where certain columns match my criteria
- I want to only view columns I'm interested

xsv provides much more functionalities than I need, but I think I will bring in more and
more into the package to make it even more useful.

* filter the rows in CSV file
Once package is loaded, run ~M-x xsv/filter~ on a buffer visiting csv file or buffer
contain valid csv format content and it will ask for the input to be used for
filtering.

The input can contain multiple criteria and each criteria should be in one of
these following syntax:
- columnA = 'regexA'
- columnB != 'regexB'

First one means search columnA where its value match regexA.
Second form means search columnB where its value NOT match regexB.

Criteria can be joined by using `&' like this:
#+begin_example
columnA = 'regexA' & columnB = 'regexB' & columnC != 'regexC'
#+end_example

It means return rows where columnA matches regexA AND columnB matches regexB AND
columnC NOT matches regexC.

The filtered result will be presented in a different buffer with prefix ~xsv-~ so
the original buffer/file are left untouched.
